### ISSUE TITLE
Is the package still maintained?

### ISSUE THREAD

**Issue by lyz-code** [midnightprioriem/mkdocs-autolinks-plugin#25]
Hi, @midnightprioriem is the package still maintained? There are some pull requests that have been open for a while.

If you can't manage it all by yourself I can help with the maintenance, but I'll need permissions to push to pypi

**Comment by midnightprioriem** [comment]
Sorry about that, haven't used MkDocs much as of late since switching jobs but I'd like to continue maintaining this, especially since people find it useful!
