### ISSUE TITLE
Links to subheadings

### ISSUE THREAD

**Issue by chrieke** [midnightprioriem/mkdocs-autolinks-plugin#4]
Love the plugin, but it appears that links to subheadings do not work with the "regular" mkdocs syntax, always getting 404. Any way to do this?

`[text link](chapter01.md#heading3)`

results in 404.

**Comment by bgwr** [comment]
Hi Christoph, I was having the same issue so I made a PR that resolves this issue. https://github.com/midnightprioriem/mkdocs-autolinks-plugin/pull/5

**Comment by midnightprioriem** [comment]
PR has been merged, version 0.2.0 has been released!
